### ISSUE TITLE
unable to compile simple httpclient wasm module

### ISSUE THREAD

**Issue by gnanasekar-somanathan** [CraneStation/wasi-sysroot#18]
I am trying to create simple httpclient wasm module to run on wasmtime
When compiling a simple httpclient using wasi-sysroot, I see that
netdb.h is not found and socket apis 'listen' , 'bind' , 'connect' , 'accept' are missing?
Are they supported?

**Comment by kubkon** [comment]
As far as I can tell, networking is not standardised nor supported just yet. See https://github.com/WebAssembly/WASI/issues/4, https://github.com/CraneStation/wasmtime/issues/70, and https://github.com/CraneStation/wasmtime/issues/69 for some discussions.

@sunfishcode, could you comment please?

**Comment by sunfishcode** [comment]
Yes, that's right. There is currently no way to create network connections, so there's no `listen`, `bind`, `connect`, or `accept`. We'd like to add them, and there is some discussion in the issues @kubkon linked to.
